// Auto-generated by calc_quant_params.py
// model: model_tools\trained_models\TinyLeNet_20251223_095246_acc99.00.pth
// normalize: 1 samples: 2000
`define Q_SHIFT 16
`define Q_MULT_CONV1 81
`define Q_MULT_CONV2 121
`define Q_MULT_FC1 89
`define Q_MULT_FC2 440
