// Auto-generated by calc_quant_params.py
// model: model_tools\trained_models\TinyLeNet_20251223_095246_acc99.00.pth
// normalize: 1 samples: 1000
`define Q_SHIFT 16
`define Q_MULT_CONV1 80
`define Q_MULT_CONV2 122
`define Q_MULT_FC1 90
`define Q_MULT_FC2 357
