// Auto-generated by weights_to_mem.py
// Array: CONV2_BIASES
// Shape: [16]
// Flatten order: row-major (C order)

module rom_CONV2_BIASES #(
    parameter integer ADDR_WIDTH = 4,
    parameter integer DATA_WIDTH = 8,
    parameter integer DEPTH = 16,
    parameter MEM_FILE = "CONV2_BIASES.mem"
) (
    input  wire                    clk,
    input  wire [ADDR_WIDTH-1:0]   addr,
    output reg  signed [DATA_WIDTH-1:0] q
);

    (* rom_style = "block" *) reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];

    initial begin
        $readmemh(MEM_FILE, mem);
    end

    always @(posedge clk) begin
        q <= $signed(mem[addr]);
    end

endmodule
