// Auto-generated by weights_to_mem.py
// Array: CONV1_BIASES
// Shape: [6]
// Flatten order: row-major (C order)

module rom_CONV1_BIASES #(
    parameter integer ADDR_WIDTH = 3,
    parameter integer DATA_WIDTH = 8,
    parameter integer DEPTH = 6,
    parameter MEM_FILE = "CONV1_BIASES.mem"
) (
    input  wire                    clk,
    input  wire [ADDR_WIDTH-1:0]   addr,
    output reg  signed [DATA_WIDTH-1:0] q
);

    (* ramstyle = "M9K" *) reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];

    initial begin
        $readmemh(MEM_FILE, mem);
    end

    always @(posedge clk) begin
        q <= $signed(mem[addr]);
    end

endmodule
