// Auto-generated by quantize_bias.py
module rom_FC2_BIASES_INT32 #(
    parameter integer ADDR_WIDTH = 4,
    parameter integer DATA_WIDTH = 32,
    parameter integer DEPTH = 16,
    parameter MEM_FILE = "FC2_BIASES_INT32.mem"
) (
    input  wire                    clk,
    input  wire [ADDR_WIDTH-1:0]   addr,
    output reg  signed [DATA_WIDTH-1:0] q
);

    (* ramstyle = "M9K" *) reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];

    initial begin
        $readmemh(MEM_FILE, mem);
    end

    always @(posedge clk) begin
        q <= $signed(mem[addr]);
    end

endmodule
