// Auto-generated by weights_to_mem.py
// Array: FC2_WEIGHTS
// Shape: [10][32]
// Flatten order: row-major (C order)

module rom_FC2_WEIGHTS #(
    parameter integer ADDR_WIDTH = 9,
    parameter integer DATA_WIDTH = 8,
    parameter integer DEPTH = 320,
    parameter MEM_FILE = "rtl/weights/FC2_WEIGHTS.mem"
) (
    input  wire                    clk,
    input  wire [ADDR_WIDTH-1:0]   addr,
    output reg  signed [DATA_WIDTH-1:0] q
);

    (* rom_style = "block" *) reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];

    initial begin
        $readmemh(MEM_FILE, mem);
    end

    always @(posedge clk) begin
        q <= $signed(mem[addr]);
    end

endmodule
